# This workflow will build a MuleSoft project
name: Build Mule App
on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add nexus repo credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
             "id": "MuleRepository",
             "username": "${{ MULE_KPMG_NEXUS_USERNAME }}",
             "password": "${{ MULE_KPMG_NEXUS_PASSWORD }}"
            }]
      
      - name: Add exchange v2 repo credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
             "id": "anypoint-exchange-v2",
             "username": "${{ secrets.MULE_EXCHANGE_USERNAME }}",
             "password": "${{ secrets.MULE_EXCHANGE_PASSWORD }}"
            }]
      
      - name: Add exchange v3 repo credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
             "id": "anypoint-exchange-v3",
             "username": "${{ secrets.MULE_EXCHANGE_USERNAME }}",
             "password": "${{ secrets.MULE_EXCHANGE_PASSWORD }}"
            }]

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 $artifactName2
      
      - name: Upload artifact 
        uses: actions/upload-artifact@master
        with:
            name: artifacts
            path: target/*.jar
        